# Generated by Django 5.2.5 on 2025-08-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favoritemovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
